# Generated by Django 3.2 on 2021-07-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0035_alter_quiz_2_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz_2',
            old_name='topic',
            new_name='Description',
        ),
    ]
