# Generated by Django 3.2 on 2021-07-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0036_rename_topic_quiz_2_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz_2',
            old_name='Description',
            new_name='topic',
        ),
    ]
