# Generated by Django 3.1.7 on 2021-05-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0031_remove_student_department_we'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Department_KNN',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
