# Generated by Django 3.1.7 on 2021-05-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0032_student_department_knn'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='DS_acc',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='KNN_acc',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='SVM_acc',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
