# Generated by Django 3.2 on 2021-07-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0034_auto_20210520_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_2',
            name='topic',
            field=models.TextField(),
        ),
    ]
